### ISSUE TITLE
Single Node Setup

### ISSUE THREAD

**Issue by dcmacleod** [sogno-platform/sogno-platform.github.io#2]
Everything seemed to work until this command
helm install -n sogno-demo --create-namespace -f rabbitmq_values.yaml rabbitmq bitnami/rabbitmq 

Error: failed to download "bitnami/rabbitmq"

**Comment by JonBau** [comment]
Thanks for raising this issue! It seems we are missing a  `helm repo update` between the `helm repo add` and the `helm install` steps.

Could you please verify that this solves the issue?

**Comment by dcmacleod** [comment]
Now I get the message after the helm install command
Error: open rabbitmq_values.yaml: no such file or directory

I have searched for this file and I do not see it. Was this file loaded as a part of the "helm repo ..." command?

**Comment by JonBau** [comment]
That file is passed to helm as an argument (`-f rabbitmq_values.yaml`). We expect that file in the current directory. This file contains overrides for default helm values. An example is provided in the docs, just below the command.

We will consider to provide an updated example and put the file in our example-deployment repo.

**Comment by leblowl** [comment]
The instructions are hopefully clearer on this now: https://github.com/sogno-platform/sogno-platform.github.io/blob/5726dd4a4bd4294df1940dfeafb5304034999c58/content/en/docs/Getting%20started/single-node.md?plain=1#L70-L88
